categories:
  - title: '🚀 Features'
    label: 'feature request'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '📖 Documentation'
    label: 'documentation'
template: |
  ## What’s Changed

  $CHANGES
